# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0004_auto_20160329_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
