# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0005_post_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='industry_type',
            field=models.CharField(choices=[('Retail & Wholesale', 'Retail & Wholesale'), ('Banking', 'Banking'), ('Health', 'Health'), ('Real Estate', 'Real Estate'), ('Travel', 'Travel'), ('Crime', 'Crime')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
