# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0006_post_industry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='industry_type',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Banking', 'Banking'), ('Social Network', 'Social Network'), ('Travel', 'Travel'), ('HealthCare', 'HealthCare'), ('Real Estate', 'Real Estate')], max_length=50),
        ),
    ]
